server:
  port: 10010

spring:
  application:
    name: server api-web-gateway
  servlet:
    multipart:
      max-file-size: 2MB
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
zuul:
  prefix: /v1
  retryable: true
  routes:
    web-service: /web/**
    auth-service: /auth/**
    search-service: /search/**
    cart-service: /cart/**
  sensitive-headers: Cookie,Set-Cookie